server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/micro1_paymentdb?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' to automatically create/update database schema
    show-sql: true     # Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Adjust dialect based on your database